### ISSUE TITLE
Add repository description

### ISSUE THREAD

**Issue by daniel-stoneuk** [IBMIXN/EmotionalMapProject#1]
It would be useful to add a description to this repository so that it shows up when displayed on profiles. 

I've looked into doing this myself, however it looks like only the owner can do this. @IBMIXN, please can you set the description of the repository to the following:

"Demonstration of IBM Watson Tone Analyser AI to visualise the tones used in UK Tweets (built with MERN stack)"

Thanks!

**Comment by IBMIXN** [comment]
No worries Daniel - all done!All the best, JohnJohn McNamaraThought Leader Certified Technical SpecialistDistinguished Technical Specialist - TOGHonorary Professor & Advanced Visiting Research FellowIBM Master InventorUK University Programs LeadPhone: 07799413848E-mail: j0nnymac@uk.ibm.comTwitter: @j0nnymacLinkedIn: https://www.linkedin.com/in/jonmcnamara/Acclaim Awards: http://bit.ly/AcclaimCredentials -----Daniel Stone <notifications@github.com> wrote: -----To: IBMIXN/EmotionalMapProject <EmotionalMapProject@noreply.github.com>From: Daniel Stone <notifications@github.com>Date: 09/03/2021 12:26PMCc: John McNamara <j0nnymac@uk.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] [IBMIXN/EmotionalMapProject] Add repository description (#1)






It would be useful to add a description to this repository so that it shows up when displayed on profiles.
I've looked into doing this myself, however it looks like only the owner can do this. @IBMIXN, please can you set the description of the repository to the following:
"Demonstration of IBM Watson Tone Analyser AI to visualise the tones used in UK Tweets (built with MERN stack)"
Thanks!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Unless stated otherwise above:IBM United Kingdom Limited - Registered in England and Wales with number 741598. Registered office: PO Box 41, North Harbour, Portsmouth, Hampshire PO6 3AU

**Comment by daniel-stoneuk** [comment]
Brilliant, thanks very much!
